application:
   name: business_rate_rest_service

saa:
  url: http://staging.saa.gov.uk/shared/webservices/vr.php?search_term={search}
  proxyHost:
  proxyPort: 80

geo-search:
  url: http://betaweb.digital.gov.uk:9092/postcodes/{postcode}
server:
  port: 9093
