application:
   name: business_rates

saa:
  url: https://www.saa.gov.uk/shared/webservices/vr.php?search_term={search}&key={key}
  key:
  username:
  password:

health:
  search: EH66QQ
  cache_time: PT1M

port: 9093
