application:
   name: business_rate_rest_service

saa:
  url: https://staging.govusers.saa.gov.uk/shared/webservices/vr.php?search_term={search}&key={key}
  key:
  username:
  password:
  proxyHost:
  proxyPort: 80

geo_search:
  url: http://devsitapp01:9092/postcodes/{postcode}
  proxyHost:
  proxyPort: 80

server:
  port: 9093
