application:
   name: business_rates

saa:
  url: https://staging.saa.gov.uk/shared/webservices/vr.php?search_term={search}&key={key}
  key:
  username:
  password:
  proxyHost:
  proxyPort: 80

server:
  port: 9093
