#!/bin/sh
. /etc/profile
set -eu
JAVA=${JAVA_HOME:-/usr}/bin/java

exec "$JAVA" \
  -Dlogback.configurationFile=/opt/business-rates/logback.xml \
  -Djava.security.properties=/opt/business-rates/security.properties \
  -jar /opt/business-rates/business-rates.jar
