#!/bin/sh -l
exec java \
  -Dlogback.configurationFile=/opt/business-rates/logback.xml \
  -Djava.security.properties=/opt/business-rates/security.properties \
  -jar /opt/business-rates/business-rates.jar \
  >> /var/log/business-rates/business-rates.log 2>&1
